[AudioPeak]
NPeriod=1024

[Client]
CountInBeat=
HeartbeatInterval=3000
SubscribeInterval=200

[Container]
AutoHorizontalScrollHold=8
CanvasPixelsPerPolygonN2=2
HeaderActiveFlagItemOnly=true
TimeScalePixelsPerBeatN1=8

[Default]
RecordFlags=NONE

[SongLyrics]
DefaultFonSize=48

